# -*- coding: utf-8 -*-
"""Projeto Anestesio.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16UCR-oLrQxN4nGojtovCsGRSepwNnGzg
"""

#Cálculo de MET (Duke acticity status index)

print("Você consegue:")

met1 = input("1. Consegue cuidar de si mesmo, isto é, comer, vestir-se, tomar banho ou ir ao banheiro? (s/n)")
if met1=="s":
  met1=2.7
else:s
  met1 = 0.0

met2 = input("2. Andar em ambientes fechados, como em sua casa? (s/n)")
if met2=="s":
  met2=1.75
else:
  met2 = 0.0

met3 = input("3. Andar um quarteirão ou dois em terreno plano? (s/n)")
if met3=="s":
 met3=2.75
else:
  met3 = 0.0

met4 = input("4. Subir um lance de escadas ou subir um morro? (s/n)")
if met4=="s":
  met4=5.5
else:
  met4 = 0.0

met5 = input("5. Correr uma distância curta? (s/n)")
if met5=="s":
  met5=8.0
else:
  met5 = 0.0

met6 = input("6. Fazer tarefas domésticas leves como tirar pó ou lavar a louça? (s/n)")
if met6=="s":
  met6=2.7
else:
  met6 = 0.0

met7 = input("7. Fazer tarefas domésticas moderadas como passar o aspirador de pó, varrer o chão ou carregar as compras de supermercado? (s/n)")
if met7=="s":
  met7=3.5
else:
  met7 = 0.0

met8 = input("8. Fazer tarefas domésticas pesadas como esfregar o chão com as mãos usando uma escova ou deslocar móveis pesados do lugar? (s/n)")
if met8=="s":
  met8=8.0
else:
  met8 = 0.0

met9 = input("9. Fazer trabalhos de jardinagem como recolher folhas, capinar ou usar um cortador elétrico de grama? (s/n)")
if met9=="s":
  met9=4.5
else:
  met9 = 0.0

met10 = input("10. Ter relações sexuais? (s/n)")
if met10=="s":
  met10=5.25
else:
  met10 = 0.0

met11 = input("11. Participar de atividades recreativas moderadas como vôlei, boliche, dança, tênis em dupla, andar de bicicleta ou fazer hidroginástica? (s/n)")
if met11=="s":
  met11=6.0
else:
  met11 = 0.0

met12 = input("12. Participar de esportes extenuantes como natação, tênis individual, futebol, basquetebol ou corrida? (s/n)")
if met12=="s":
  met12=7.5
else:
  met12 = 0.0

MET = met1+met2+met3+met4+met5+met6+met7+met8+met9+met10+met11+met12
print("Pontuação:" +str(MET))
VO2 = 0.43*MET + 9.6
print("VO2 máx:"+str(VO2))

#Condições de alto risco perioperatório
sca = input("Síndrome coronariana aguda há menos de 60 dias? (s/n)")
if sca=="s":
  sca=1.0
else:
  sca=0.0

icg = input("Insuficiencia cardíaca grave? (s/n)")
if icg=="s":
  igc=1.0
else:
  igc=0.0

ag = input("Arritmias graves (BAVT,TV,FV)? (s/n)")
if ag=="s":
  ag=1.0
else:
  ag=0.0

vis = input("Valvuloparias importantes sintomáticas? (s/n)")
if vis=="s":
  vis=1.0
else:
  vis=0.0

hp = input("Hipertensão pulmonar? (s/n)")
if hp=="s":
  hp=1.0
else:
  hp=0.0

ae = input("Angina enstável CCS III-IV (angina com limitação das atividades habituais)? (s/n)?")
if ae=="s":
  ae=1.0
else:
  ae=0.0

fafc = input("FA com FC > 120bpm? (s/n)")
if fafc=="s":
  fafc=1.0
else:
  fafc=0.0

pas = input("PAS>180mmHg ou PAD > 110mmHg? (s/n)")
if pas=="s":
  pas=1.0
else:
  pas=0.0

saa = input("Síndromes aórticas agudas? (s/n)")
if saa=="s":
  saa=1.0
else:
  saa=0.0

carp = sca + igc + ag + vis + hp + ae + fafc + pas + saa
if carp>1.0:
  print("CONDIÇÃO DE ALTO RISCO PERIOPERATÓRIO!")

#Escore de Lee
el1 = input("Operação intraperitoneal? (s/n) ")
if el1 == "s":
 el1 = 1.0
else:
 el1 = 0.0

el2 = input("intratorácica ou vascular suprainguinal? (s/n) ")
if el2 == "s":
 el2 = 1.0
else:
 el2 = 0.0

el3 = input("História de doença arterial coronariana? (s/n) ")
if el3 == "s":
 el3 = 1.0
else:
 el3 = 0.0

el4 = input("História de insuficiência cardíaca? (s/n) ")
if el4 == "s":
 el4 = 1.0
else:
 el4 = 0.0

el5 = input("História de doença cerebrovascular? (s/n) ")
if el5 == "s":
 el5 = 1.0
else:
 el5 = 0.0

el6 = input("Diabetes mellitus com insulinoterapia? (s/n) ")
if el6 == "s":
 el6 = 1.0
else:
 el6 = 0.0

el7 = input("Creatinina pré-operatória >2,0mg/dL? (s/n) ")
if el7 == "s":
 el7 = 1.0
else:
 el7 = 0.0

EL = el1 + el2 + el3 + el4 + el5 + el6 + el7
if EL == 0.0:
  print("Risco baixo (0,4%)")
if EL == 1.0:
  print("Risco baixo (0,9%)")
if EL == 2.0:
  print("Risco moderado (6,6%)")
if EL > 2.0:
  print("Risco alto (11%)\n Dosagem de trponina operatória e após 48h\n Dosagem de BNP\n Pós operatório imediato em UTI")

print("Complicações cardíacas maiores incluem: infarto do miocárdio, edema pulmonar, fibrilação ventricular ou parada cardíaca primária, e bloqueio cardíaco completo até o 5º dia pós-operatório.")
if el6 == 1.0:
  print("Manter glicemia perioperatória entre 80mg/dl - 180 mg/dl \n Não usar hipoglicemiante oral no dia da cirurgia \n Se utiliza insulina NPH, fazer metade da dose na manhã da cirurgia \n Monitorizar glicemia de 4/4Hs \n Sugerimos fazer testes de glicose sanguínea e HbA1c em pacientes com diagnóstico de diabetes mellitus e em pacientes agendados para cirurgia ortopédica ou vascular de grande porte \n Sugerimos fazer uma avaliação cuidadosa das vias aéreas em pacientes com diabetes de longa data.")

#Escore de AUB-HAS2
ej1 = input("Idade igual ao maior que 75? (s/n)")
if ej1 == "s":
 ej1 = 1.0
else:
 ej1 = 0.0

ej2 = input("Hemoglobina menor ou igual à 12? (s/n)")
if ej2 == "s":
  ej2 = 1.0
else:
  ej2 = 0.0

ej3 = input("História de cardiopatia (infarto prévio, angioplastia coronariana, cirurgia cardíaca, insuficiência cardíaca, valvopatia moderada/importante na ecografia)? (s/n)")
if ej3 == "s":
  ej3 = 1.0
else:
  ej3 = 0.0

ej4 = input("Angina ou dispnéia (dor torácica opressiva aos esforços, falta de ar aos esforços habituais)? (s/n)")
if ej4 == "s":
  ej4 = 1.0
else:
  ej4 = 0.0

ej5 = input("Cirurgia vascular? (s/n)")
if ej5 == "s":
  ej5 = 1.0
else:
  ej5 = 0.0

ej6 = input("Cirurgia de emergência? (s/n)")
if ej6 == "s":
  ej6 = 1.0
else:
  ej6 = 0.0

#Risco Instrínsico da cirurgia
ri1 = input("Procedimento ambulatorial, endoscópico, mama, catarata, superficiais? (s/n) ")
ri2 = input("Procedimento de urgência, emergência, vasculares arteriais EXCETO endarterectomia de carótida e correção endovascular de Aorta? (s/n) ")
if ri1 == "s":
  print("RISCO BAIXO")
if ri2 == "s":
  print("RISCO ALTO")
if ri1 =="n" and ri2 =="n":
  print("RISCO MODERADO")

#Fluxo de condutas
if ri2 == "s":
  print("Medidas para redução de risco")
if carp > 0.0:
  print("Adiar e estabiliar")
print("Escore de Lee: "+ str(EL))
if EL <= 1.0:
  print("sem necessidade de prova isquêmica")
else:
  print("Considerar prova de isquemia se:\n Cirurgia vascular arterial \n Cururgia de risco intermediário e baixa capacidade funcional \n Se DAC/Risco DAC - tropo + ECG + UTI")

#Sugestão de condutas risco moderado e alto
if ri1 =="n" and ri2 =="n" and sca=="s":
  print("Solicitar troponina ultrasensível pré operatória e até 48hs-72hs pós operatória\n ECG 48hs - 72hs pós operatorio\n pós imediato em UTI se possível")

if ri1 =="n" and ri2 =="n" and MET<4.0:
  print("Considerar prova isquêmica")

if ri1 =="n" and ri2 =="n":
  print("Considerar prova isquêmica")
  

if ri2 == "s" and sca=="s":
  print("Solicitar troponina ultrasensível pré operatória e até 48hs-72hs pós operatória\n ECG 48hs - 72hs pós operatorio\n pós imediato em UTI se possível")

if ri2 =="s" and MET<4:
  print("Considerar prova isquêmica")

if ri2 =="s":
  print("considerar a opção de quantificar o BNP para a obtenção de informações prognósticas independentes sobre eventos cardíacos perioperatórios e tardios em pacientes de alto risco.")

#Trombose venosa profunda

fr11 = input("idade entre 41 - 60 anos? (s/n)")
if fr11=="s":
  fr11=1.0
else:
  fr11=0.0

fr12= input("cirurgia menor planejada sob anestesia geral ou regional < 45 min? (s/n)")
if fr12=="s":
  fr12=1.0
else:
  fr12=0.0  
  
fr13=input("Histórico (<1 mês ) de cirurgia sob anestesia geral ou regional > 45 min? (s/n)")
if fr13=="s":
  fr13=1.0
else:
  fr13=0.0

fr14=input("Veias varicosas visíveis? (s/n)")
if fr14=="s":
  fr14=1.0
else:
  fr14=0.0

fr15=input("Doença inflamatória intestinal (Doença de Chron ou colite ulcerativa)? (s/n)")
if fr15=="s":
  fr15=1.0
else:
  fr15=0.0  

fr16=input("Edema de membro inferior atual? (s/n)")
if fr16=="s":
  fr16=1.0
else:
  fr16=0.0  

fr17=input("IMC > 25? (s/n)")
if fr17=="s":
  fr17=1.0
else:
  fr17=0.0

fr18=input("Infarto agudo do miocárdio? (s/n)")
if fr18=="s":
  fr18=1.0
else:
  fr18=0.0

fr19=input("DPOC? (s/n)")
if fr19=="s":
  fr19=1.0
else:
  fr19=0.0
  
fr110=input("Insuficiência Cardíaca Congestiva (< 1 mês)? (s/n)")
if fr110=="s":
  fr110=1.0
else:
  fr110=0.0
  
fr111=input("Sepse (< 1 mês)? (s/n)")
if fr111=="s":
  fr111=1.0
else:
  fr111=0.0
  
fr112=input("Doença pulmonar severa < 1 mês - ex Pneumonia? (s/n)")
if fr112=="s":
  fr112=1.0
else:
  fr112=0.0
  
fr113=input("Paciente em cuidados médicos atualmente em repouso? (s/n)")
if fr113=="s":
  fr113=1.0
else:
  fr113=0.0
  
fr114=input("Uso de terapia anticoncepcional ou reposição hormonal? (s/n)")
if fr114=="s":
  fr114=1.0
else:
  fr114=0.0
  
fr115=input("Gestão ou Pós-parto < 1 mês? (s/n)")
if fr115=="s":
  fr115=1.0
else:
  fr115=0.0 

fr116=input("Histórico de criança natimorta inexplicada, aborto espontâneo recorrente (>2), nascimento prematuro com toxemia ou criança com restrição de crescimento? (s/n)")
if fr116=="s":
  fr116=1.0
else:
  fr116=0.0
  
fr117=input("Outro fator de risco? (s/n)")
if fr117=="s":
  fr117=1.0
else:
  fr117=0.0
  
fr21=input("Idade entre 61 - 74 anos? (s/n)")
if fr21=="s":
  fr21=1.0
else:
  fr21=0.0
  
fr22=input("cirurgia de artroscopia? (s/n)")
if fr22=="s":
  fr22=1.0
else:
  fr22=0.0
  
fr23=input("Malignidade (presente ou prévia)? (s/n)")
if fr23=="s":
  fr23=1.0
else:
  fr23=0.0
  
fr24=input("cirurgia sob anestesia geral ou regional > 45 min? (s/n)")
if fr24=="s":
  fr24=1.0
else:
  fr24=0.0
  
fr25=input("paciente confinado ao leito >72 horas? (s/n)")
if fr25=="s":
  fr25=1.0
else:
  fr25=0.0
  
fr26=input("imobilização gessada <1 mês? (s/n)")
if fr26=="s":
  fr26=1.0
else:
  fr26=0.0
  
fr27=input("acesso venoso central? (s/n)")
if fr27=="s":
  fr27=1.0
else:
  fr27=0.0
  
fr31=input("idade > 75 anos? (s/n)")
if fr31=="s":
  fr31=1.0
else:
  fr31=0.0
  
fr32=input("histórico de TVP/TEP? (s/n)")
if fr32=="s":
  fr32=1.0
else:
  fr32=0.0
  
fr33=input("Histórico Familiar de Trombose? (s/n)")
if fr33=="s":
  fr33=1.0
else:
  fr33=0.0
  
fr34=input("Fator V de Leiden positivo? (s/n)")
if fr34=="s":
  fr34=1.0
else:
  fr34=0.0
  
fr35=input("Protrombina 20210A positivo? (s/n)")
if fr34=="s":
  fr34=1.0
else:
  fr35=0.0
  
fr36=input("Homocisteina sérica elevada? (s/n)")
if fr36=="s":
  fr36=1.0
else:
  fr36=0.0
  
fr37=input("Anticoagulante lúdico positivo? (s/n)")
if fr37=="s":
  fr37=1.0
else:
  fr37=0.0
  
fr38=input("Anticorpo anticardiolipina positivo? (s/n)")
if fr38=="s":
  fr38=1.0
else:
  fr38=0.0
  
fr39=input("Trombocitopenia induzida por heparina? (s/n)")
if fr39=="s":
  fr39=1.0
else:
  fr39=0.0
  
fr310=input("Outra trombofilia congênita ou adquirida? (s/n)")
if fr310=="s":
  fr310=1.0
else:
  fr310=0.0
  
fr51=input("Artroplastia eletiva maior de extremidade inferior? (s/n)")
if fr51=="s":
  fr51=1.0
else:
  fr51=0.0

fr52=input("Fratura de quadril, pelve ou perna < 1 mês? (s/n)")
if fr52=="s":
  fr52=1.0
else:
  fr52=0.0

fr53=input("Acidente Vascular Encefálico < 1 mês? (s/n)")
if fr53=="s":
  fr53=1.0
else:
  fr53=0.0
  
fr54=input("Trauma múltiplo < 1 mês? (s/n)")
if fr54=="s":
  fr54=1.0
else:
  fr54=0.0
  
fr55=input("Lesão aguda de medula espinhal (paralisia) < 1 mes? (s/n)")
if fr55=="s":
  fr55=1.0
else:
  fr55=0.0

FR = fr11+fr12+fr13+fr14+fr15+fr16+fr17+fr18+fr19+fr110+fr111+fr112+fr113+fr114+fr115+fr116+fr117+fr21+fr22+fr23+fr24+fr25+fr26+fr27+nfr31+fr32+fr33+fr34+fr35+fr36+fr37+fr38+fr39+fr310+fr51+fr52+fr53+fr54+fr55
if FR==0.0:
  print("Risco muito baixo:\nCuidados: - Deambulação frequente precoce apenas ou a critério da equipe cirúrgica\nDispositivos de compressão pneumática ou meias de compressão graduadas\nDURAÇÃO DA RECOMENDAÇÃO:Durante hospitalização")

if FR==1.0 or FR==2.0:
  print("Risco baixo:\nCUIDADOS: Deambulação frequente precoce e\n Dispositivos de compressão pneumática ou meias de compressão graduadas\nDURAÇÃO DA RECOMENDAÇÃO:Durante hospitalização")

if FR==3.0 or FR==4.0:
  print("Risco moderado\nCUIDADOS: Deambulação frequente precoce e\nDispositivos de compressão pneumática ou meias de compressão graduadas ou\nEnoxaparina 40 mg sc 1x/dia ou\n heparina 5000 un 12/12 horas\nnDURAÇÃO DA RECOMENDAÇÃO: Durante hospitalização")

if FR>4.0 and FR<9.0:
  print("risco alto\nCUIDADOS: compressão pneumática intermitente e\nEnoxaparina 40 mg sc 1x/dia ou\nheparina 5000 un 8/8 horas\nDURAÇÃO DA RECOMENDAÇÃO: 7-10 dias")

if FR>9.0:
  print("RISCO MUITO ALTO:\nCUIDADOS: compressão pneumática intermitente e\n Enoxaparina 40 mg sc 1x/dia ou \nheparina 5000 un 8/8 horas\nDURAÇÃO DA RECOMENDAÇÃO: 30 dias")

#CLinical Frailty Scale

cfs1 = input("Essa pessoa possui uma doença terminal com expectativa de vida < 6 meses? (s/n)")
if cfs1 == "s":
  print("9 - Doente terminal")

cfs2 = input("Essa pessoa é completamente dependente e está se aproximando do fim da vida? (s/n)")
if cfs2 == "s":
  print("8 - Severamente Frágil")

cfs3 = input("Essa pessoa é completamente dependente no seus cuidados pessoais? (s/n)")
if cfs3 == "s":
  print("7 - Muito frágil")

cfs4 = input("Essa pessoa necessita de ajuda para qualquer atividade ao ar livre, arrumar a casa e/ou tomar banho? (s/n?)")
if cfs4 == "s":
  print("6 - moderadamente frágil")

cfs5 = input("Essa pessoa necessita ajuda com: atividades instumentais do dia a dia, ex: finanças, contabilidade, transporte, trabalhos domésticos pesados, preparação de refeições ou medicações? (s/n)")
if cfs5 == "s":
  print("5 - levemente frágil")

cfs6 = input("Essa pessoa, enquanto não dependente de outros, os sintomas dessa pessoas, se limitam às suas atividades? (s/n)")
if cfs6 == "s":
  print("4 - vulnerável")

cfs7 = input("essa pessoa tem problemas médicos que estão bem controlados, mas não são regularmente ativos , além de caminhadas rotineiras? (s/n)")
if cfs7 == "s":
  print("3 - regular")

cfs8 = input("essa pessoa não tem sintomas de doença ativa e se exercita apenas ocasionalmente? (s/n)")
if cfs8 == "s":
  print("2 - ativo")

cfs9 = input("essa pessoa tem atividade física regular e apresenta-se em forma para sua faixa etária? (s/n)")
if cfs9 == "s":
  print("1 - muito ativo")

#Delirium

fp1=input("IDADE	60-69? (s/n)")
if fp1=="s":
  fp1=0.0
if fp1=="n":
  fp1=1.0

fp2=input("70-79? (s/n)")
if fp2=="s":
  fp1=1.0
if fp2=="n":
  fp1=0.0

fp3=input("80 OU MAIS? (s/n)")
if fp3=="s":
  fp1=2.0
if fp3=="n":
  fp1=0.0

fp4=input("ATIVIDADES DIÁRIAS	AUTO-SUFICIENTE? (s/n)")
if fp4=="s":
  fp4=0.0
if fp4=="n":
  fp4=1.0

fp5=input("NECESSITA DE AUXÍLIO? (s/n)")
if fp5=="n":
  fp5=0.0
if fp5=="s":
  fp5=1.0

fp6=input("CONSUMO AUMENTADO DE ÁLCOOL 	NÃO? (s/n)")
if fp6=="n":
  fp6=0.0
if fp6=="s":
  fp6=1.0

fp8=input("HISTÓRIA DE DELIRIUM	NÃO? (s/n)")
if fp8=="n":
  fp8=0.0
if fp8=="s":
  fp8=1.0

fp10=input("CIRURGIA ABERTA	NÃO? (s/n)")
if fp10=="n":
  fp10=0.0
if fp10=="s":
  fp10=1.0

fp12=input("CIRURGIA DE EMERGÊNCIA	NÃO? (s/n)")
if fp12=="n":
  fp12=0.0
if fp12=="s":
  fp12=1.0


fp14=input("PROTEÍNA-C REATIVA	< 10mg/dL? (s/n)")
if fp14=="n":
  fp14=0.0
if fp14=="s":
  fp14=1.0


FP = fp1 + fp4 + fp5 + fp6 + fp8 + fp10 + fp12 + fp14
print(FP)
if FP<6.0:
  print("BAIXO RISCO")
if FP>5.0:
  print("ALTO RISCO")

print("condutas pré-operatórias:	1-Evitar jejum prolongado de líquidos [6hs] 2- Avaliação geriátrica e otimização clínica")
print("condutas intraoperatórias 1-anestesia multimodal poupadora de opióides (*uso de cetamina 0,2-05 mg/Kg não aumentou a incidência) 2- Evitar Hipotermia 3- uso de dexmedetomidina se possível 4- monitorização da consciência 5- uso de paracetamol e AINES")
print("Medicações que aumentam o risco de Delirium : Gabapentinóides, Anti depressivos triciclicos, benzodiazepínicos, anticolinérgicos (escopolamina)")
print("OUTRAS CONDIÇÕES que predispõe ao Delirium: {Cirurgia aberta, cirurgia de emergência e cirurgia abdominal}{desidratação, hipo/hipernatremia,hipotermia,dor pós operatória,doença cardiovascular,DM}" )

#Conduta DAC
dac1 = input("Paciente com doença coronariana arterial? (s/n)")
if dac1 == "s":
   print("considerar iniciar estatina no pr operatorio ")

dac2 = input("Paciente com pós infarto agudo do miocardio? (s/n)")
if dac2 == "s":
   print("Se possível aguardar pelo menos 60 dias pós infarto, tempo ideal pelo menos 180 dias.")

#Hipertensão
hiper = input("Pacientes com hipertensão arterial? (s/n)")
if ej5 == "s":
  print("Ter como objetivo manter PA < 180 x 110mmHg")

#Conduta DM
db = input("Paciente com diabete melitius? (s/n)")
if db=="s":
  print("Manter glicemia perioperatória entre 80mg/dl - 180 mg/dl\n Não usar hipoglicemiante oral no dia da cirurgia\n SE utiliza insulina NPH, fazer metade da dose na manhã da cirurgia\n Monitorizar glicemia de 4/4Hs\n - testes pré operatórios de glicose sanguínea e HbA1c em pacientes com diagnóstico de diabetes mellitus e em pacientes agendados para cirurgia ortopédica ou vascular de grande porte\n - Avaliação cuidadosa das vias aéreas em pacientes com diabetes de longa data (dificuldade de mobilização)")

###############################################################################

#Capacidade funcional
#mostrar matriz cp
cp = input("Indicar a capacidade funcional (1-12): ")
if int(cp)<3:
  print("RISCO CARDIOVASCULAR!")

#Grau de fragilidade
print("Paciente é capaz de realizar as seguintes atividades sem ajuda:")

gf1 = input("Comer (s/n) ")
if gf1 == "s":
 gf1 = 1.0
else:
 gf1 = 0.0

gf2 = input("vestir-se (s/n) ")
if gf2 == "s":
 gf2 = 1.0
else:
 gf2 = 0.0

gf3 = input("tomar banho (s/n) ")
if gf3 == "s":
 gf3 = 1.0
else:
 gf3 = 0.0

gf4 = input("usar o banheiro (s/n) ")
if gf4 == "s":
 gf4 = 1.0
else:
 gf4 = 0.0

gf5 = input("locomover-se (s/n) ")
if gf5 == "s":
 gf5 = 1.0
else:
 gf5 = 0.0

gf6 = input("continência urinária (s/n) ")
if gf6 == "s":
 gf6 = 1.0
else:
 gf6 = 0.0

GF2 = input("andar uma distância de 5 metros em menos de 6 segundos sem ter ajuda e sem usar nenhum tipo de aparato (ex: bengala)? (s/n) ")
if GF2 == "s":
 GF2 = 1.0
else:
 GF2 = 0.0

GF1 = gf1+gf2+gf3+gf4+gf5+gf6
if GF1==6.0 and GF2==1.0:
  print("SEM FRAGILIDADE")
if GF1<6.0 or GF==0.0:
  print("FRAGILIDADE DISCRETA")
if GF1<5.0:
  print("FRAGILIDADE MODERADA/IMPORTANTE")

#Estratificação de Risco Náuseas e vômitos
x = input("Mulher? (s/n)")
if x == "s":
 x = 1.0
else:
 x = 0.0
y = int(input("Idade? "))
if y < 50:
 y = 1.0
else:
 y = 0.0 
z = input("História de NVPO?(s/n) " )
if z == "s":
 z = 1.0
else:
 z = 0.0
w = input("Náusea na sala de recuperação?(s/n) ")
if w == "s":
 w = 1.0
else:
 w = 0.0
v = input("Uso de opioides da sala de recuperação?(s/n) ")
if v == "s":
 v = 1.0
else:
 v = 0.0

#Escore de risco
q = x + y + z + w + v
print("Escore de risco: "+ str(q))
#Recomendação
if q<3:
 print("Sugestão 1")
if q>2:
 print("Sugestão 2")

#Hipetermia maligna?
n = input("Nome do paciente: ")
if "Blemer" or "blemer" in n:
  print("HIPETERMIA MALÍGNA!!!")
else:
  print("SEM HM GENÉTICA")