# Generated by Django 3.2.5 on 2021-08-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='teste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_teste', models.CharField(max_length=100)),
                ('tipo_teste', models.CharField(max_length=100)),
                ('orelha_direita_teste', models.CharField(max_length=100)),
                ('orelha_esquerda_teste', models.CharField(max_length=100)),
                ('conduta_teste', models.CharField(max_length=100)),
                ('observacoes', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['data_teste'],
            },
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['cpf', 'nome'],
            },
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
