# Generated by Django 3.2.5 on 2021-08-30 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20210830_0034'),
    ]

    operations = [
        migrations.DeleteModel(
            name='teste',
        ),
        migrations.DeleteModel(
            name='usuario',
        ),
    ]
