# Generated by Django 3.2.5 on 2021-08-31 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0004_auto_20210830_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('sobrenome', models.CharField(max_length=100, verbose_name='Sobrenome')),
                ('Telefone', models.CharField(max_length=19, verbose_name='Telefone')),
                ('Telefone2', models.CharField(max_length=19, verbose_name='Telefone2')),
                ('cnes', models.CharField(max_length=100, verbose_name='CNES ou CNPJ')),
                ('Especialidade', models.CharField(max_length=100, verbose_name='Especialidade ')),
                ('registro', models.CharField(choices=[('Escolher', 'Escolher'), ('CRM', 'CRM'), ('CRFa', 'CRFa'), ('CREFITO', 'CREFITO'), ('COREN', 'COREN'), ('CRP', 'CRP'), ('CRAS', 'CRAS'), ('CRO', 'CRO'), ('Outros', 'Outros')], max_length=15)),
                ('Registro_numero', models.CharField(max_length=100, verbose_name='Registro')),
            ],
            options={
                'ordering': ['cpf', 'nome'],
            },
        ),
    ]
