# Generated by Django 3.2.5 on 2021-09-01 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeNeonato', models.CharField(max_length=100, verbose_name='Nome')),
                ('sobreNeonato', models.CharField(max_length=100, verbose_name='Sobrenome')),
                ('Parto', models.CharField(choices=[('Normal', 'Normal'), ('Cesárea', 'Cesárea')], max_length=15, verbose_name='Tipo de Parto')),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=15)),
                ('apgar', models.CharField(choices=[('1 APGAR', '1 APGAR'), ('2 APGAR', '2 APGAR'), ('3 APGAR', '3 APGAR'), ('4 APGAR', '4 APGAR'), ('5 APGAR', '5 APGAR'), ('6 APGAR', '6 APGAR'), ('7 APGAR', '7 APGAR'), ('8 APGAR', '8 APGAR'), ('9 APGAR', '9 APGAR'), ('10 APGAR', '10 APGAR')], max_length=15)),
                ('apgar2', models.CharField(choices=[('1 APGAR', '1 APGAR'), ('2 APGAR', '2 APGAR'), ('3 APGAR', '3 APGAR'), ('4 APGAR', '4 APGAR'), ('5 APGAR', '5 APGAR'), ('6 APGAR', '6 APGAR'), ('7 APGAR', '7 APGAR'), ('8 APGAR', '8 APGAR'), ('9 APGAR', '9 APGAR'), ('10 APGAR', '10 APGAR')], max_length=15)),
                ('irda', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=15)),
                ('obito', models.CharField(max_length=6, verbose_name='òbito')),
                ('obs', models.CharField(max_length=100000)),
                ('nomeResponsavel', models.CharField(max_length=100, verbose_name='Nome do Responsavel')),
                ('cpf_responsavel', models.CharField(max_length=14, verbose_name='CPF Responsavel')),
                ('email_responsavel', models.EmailField(max_length=100, verbose_name='Email do Responsavel')),
                ('Telefone_respnsavel', models.CharField(max_length=15, verbose_name='Telefone')),
                ('Telefone_respnsavel2', models.CharField(max_length=15, verbose_name='Telefone')),
                ('cep', models.CharField(max_length=10)),
                ('Endereco', models.CharField(max_length=150)),
                ('Numero', models.CharField(max_length=150)),
                ('Bairro', models.CharField(max_length=150)),
                ('cidade', models.CharField(max_length=150)),
                ('uf', models.CharField(max_length=150)),
                ('complemento', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ['nomeNeonato'],
            },
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Telefone',
            field=models.CharField(max_length=15, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Telefone2',
            field=models.CharField(max_length=15, verbose_name='Telefone2'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='registro',
            field=models.CharField(choices=[('CRM', 'CRM'), ('CRFa', 'CRFa'), ('CREFITO', 'CREFITO'), ('COREN', 'COREN'), ('CRP', 'CRP'), ('CRAS', 'CRAS'), ('CRO', 'CRO'), ('Outros', 'Outros')], max_length=15),
        ),
    ]
